version: '3'
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    networks:
    - database
    volumes:
      - ./db-init/db.sql:/docker-entrypoint-initdb.d/db.sql
  api:
    container_name: api
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      spring_datasource_url: jdbc:postgresql://database:5432/postgres
      spring_datasource_username: postgres
      spring_datasource_password: postgres
    networks:
      - api
      - database
  fe:
    container_name: fe
    build:
      context: ../frontend/attendi-fe
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - fe
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
networks:
  fe:
  api:
  database: