version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/db.sql:/docker-entrypoint-initdb.d/db.sql
  api:
    image: spring-boot-image
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      spring_datasource_url: jdbc:postgresql://database:5432/postgres
      spring_datasource_username: postgres
      spring_datasource_password: postgres
